# Importing Required Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Reading Data

In [2]:
train_df = pd.read_excel('trainset_60.xls', header = None)
test_df = pd.read_excel('testset_20.xls', header = None)
validate_df = pd.read_excel('validate_20.xls', header = None)

# Exploring Data

In [3]:
# having a look at the first 10 rows
train_df

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,-0.979398,-0.995127,-0.990196,-0.989030,-0.985714,-0.988102,-0.974542,-0.999877,-0.960534,-0.997655,...,-0.944312,-0.968071,0.829432,0.954474,0.949455,0.878967,0.922631,0.901529,0.437854,1
1,-0.977015,-0.991844,-0.986153,-0.985407,-0.987160,-0.988733,-0.975126,-0.993990,-0.971040,-0.999994,...,-0.969842,-0.958990,0.686442,0.956677,0.967947,0.843794,0.959571,0.871526,0.377164,1
2,-0.977214,-0.995317,-0.988394,-0.990684,-0.984565,-0.979365,-0.976852,-0.996106,-0.970861,-0.995631,...,-0.984499,-0.991658,0.850845,0.962474,0.867820,0.924592,0.920010,0.753506,0.662129,1
3,-0.975696,-0.993981,-0.987117,-0.986670,-0.988736,-0.987517,-0.976174,-0.978601,-0.985156,-0.999917,...,-0.979154,-0.983933,0.573253,0.932368,0.895771,0.784650,0.992828,0.946348,0.461835,1
4,-0.973372,-0.991760,-0.985759,-0.987134,-0.987139,-0.983848,-0.974375,-0.994321,-0.986975,-0.997641,...,-0.992241,-0.981634,0.894333,0.983818,0.925090,0.908474,0.927931,0.901710,0.590814,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19771,-0.957070,-0.954979,-0.955659,-0.966469,-0.984032,-0.981845,-0.963891,-0.955994,-0.945090,-0.957996,...,-0.996998,-0.988493,0.237340,0.165183,0.192927,0.585930,0.857968,0.925022,0.374319,8
19772,-0.955592,-0.953720,-0.954084,-0.962719,-0.984188,-0.985089,-0.962622,-0.937544,-0.932634,-0.938115,...,-0.999357,-0.997036,0.391805,0.287853,0.217807,0.680672,0.887230,0.959422,0.348198,8
19773,-0.953191,-0.955371,-0.953880,-0.956322,-0.976542,-0.987486,-0.966559,-0.939003,-0.944504,-0.937217,...,-0.992326,-0.992933,0.085243,0.235210,0.085468,0.339082,0.803739,0.974141,0.341012,8
19774,-0.956155,-0.958812,-0.955644,-0.965950,-0.987854,-0.985145,-0.964259,-0.946520,-0.964671,-0.944348,...,-0.998761,-0.997062,0.384693,0.313906,0.428777,0.691283,0.885074,0.955335,0.413617,8
19775,-0.956173,-0.956803,-0.954443,-0.964385,-0.981263,-0.981871,-0.966781,-0.956403,-0.951157,-0.949384,...,-0.999248,-0.975193,0.138451,0.182601,0.112378,0.538713,0.885566,0.940463,0.273441,8

In [4]:
# train_data analysis -> shape, columns, description and info
print("\n\nshape of the train_data (in (rows, columns) form) : ", train_df.shape)
print()
print("\n\ncolumns of the train_data : \n", train_df.columns)
print('\n\nDescription of the train_data : \n\nIt includes count, mean,standard deviation, minimum, maximum etc of each columns\n')
print(train_df.info())
print('\n\nso according to the previous result we do not have any missing or NAN data.....so we don\'t have to worry about data cleaning')
train_df.describe()

shape of the train_data (in (rows, columns) form) :  (19776, 43)



columns of the train_data :
 Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42],
           dtype='int64')


Description of the train_data :

It includes count, mean,standard deviation, minimum, maximum etc of each columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19776 entries, 0 to 19775
Data columns (total 43 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       19776 non-null  float64
 1   1       19776 non-null  float64
 2   2       19776 non-null  float64
 3   3       19776 non-null  float64
 4   4       19776 non-null  float64
 5   5       19776 non-null  float64
 6   6       19776 non-null  float64
 7   7       19776 non-null  float64
 8   8       19776 non-null  float64
 9   9       19776 non-null  float64
 10  10      19776 non-null  float64
 11  11      19776 non-null  float64
 12  12      19776 non-null  float64
 13  13      19776 non-null  float64
 14  14      19776 non-null  float64
 15  15      19776 non-null  float64
 16  16      19776 non-null  float64
 17  17      19776 non-null  float64
 18  18      19776 non-null  float64
 19  19      19776 non-null  float64
 20  20      19776 non-null  float64
 21  21      19776 non-null  float64
 22  22      19776 non-null  float64
 23  23      19776 non-null  float64
 24  24      19776 non-null  float64
 25  25      19776 non-null  float64
 26  26      19776 non-null  float64
 27  27      19776 non-null  float64
 28  28      19776 non-null  float64
 29  29      19776 non-null  float64
 30  30      19776 non-null  float64
 31  31      19776 non-null  float64
 32  32      19776 non-null  float64
 33  33      19776 non-null  float64
 34  34      19776 non-null  float64
 35  35      19776 non-null  float64
 36  36      19776 non-null  float64
 37  37      19776 non-null  float64
 38  38      19776 non-null  float64
 39  39      19776 non-null  float64
 40  40      19776 non-null  float64
 41  41      19776 non-null  float64
 42  42      19776 non-null  int64
dtypes: float64(42), int64(1)
memory usage: 6.5 MB
None


so according to the previous result we do not have any missing or NAN data.....so we don't have to worry about data cleaning

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
count,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,...,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000,19776.000000
mean,-0.967026,-0.973764,-0.974524,-0.976156,-0.983901,-0.988070,-0.973452,-0.978525,-0.984788,-0.987960,...,-0.980891,-0.989073,0.564115,0.664121,0.719527,0.759257,0.867718,0.883626,0.686217,4.481240
std,0.006484,0.010313,0.009442,0.008488,0.007903,0.007623,0.006377,0.013154,0.013629,0.014114,...,0.016387,0.008572,0.221523,0.235575,0.242570,0.219767,0.190823,0.176055,0.193588,2.283797
min,-0.992978,-0.999390,-0.997876,-0.996088,-0.999096,-0.999254,-0.993117,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-0.180626,-0.126708,-0.181142,-0.127326,-0.489089,-0.270295,-0.028229,1.000000
25%,-0.970863,-0.978363,-0.980804,-0.982848,-0.988560,-0.992707,-0.977604,-0.988487,-0.995137,-0.998247,...,-0.992149,-0.995838,0.394830,0.515154,0.614077,0.703962,0.894333,0.901884,0.570382,2.000000
50%,-0.966362,-0.972209,-0.976080,-0.976374,-0.985349,-0.989704,-0.973525,-0.979734,-0.988842,-0.993705,...,-0.985227,-0.990942,0.583453,0.702542,0.812585,0.837481,0.928841,0.951196,0.722852,4.000000
75%,-0.962392,-0.966902,-0.967325,-0.970279,-0.982122,-0.985911,-0.968991,-0.970269,-0.977581,-0.982024,...,-0.974966,-0.984082,0.739326,0.862295,0.901755,0.906237,0.951522,0.976615,0.836068,6.000000
max,-0.949991,-0.947634,-0.948779,-0.953095,-0.952139,-0.956284,-0.955042,-0.917977,-0.912365,-0.916309,...,-0.865086,-0.931140,0.992636,0.999986,0.998774,0.999928,0.999999,1.000000,0.998930,8.000000

# Preparing Data For Classification

In [5]:
# Converted the data frame into numpy array
train_data = np.array(train_df)
test_data = np.array(test_df)
validate_data = np.array(validate_df)

x_train = train_data[:, : train_data.shape[1] - 1]
y_train = train_data[:, train_data.shape[1] - 1]

x_validate = validate_data[:, : validate_data.shape[1] - 1]
y_validate = validate_data[:, validate_data.shape[1] - 1]

x_test = test_data[:, : test_data.shape[1] - 1]
y_test = test_data[:, test_data.shape[1] - 1]

In [6]:
# Feature Scaling
scaler = StandardScaler().fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)
x_validate_scaled = scaler.transform(x_validate)

In [7]:
x_train_scaled_df = pd.DataFrame(x_train_scaled)
y_train_df = pd.DataFrame(y_train)

x_validate_scaled_df = pd.DataFrame(x_validate_scaled)
y_validate_df = pd.DataFrame(y_validate)

x_test_scaled_df = pd.DataFrame(x_test_scaled)
y_test_df = pd.DataFrame(y_test)

# Saving the scaled training Data for further use

In [8]:
x_train_scaled_df.to_csv('x_train.csv')
x_validate_scaled_df.to_csv('x_validate.csv')
x_test_scaled_df.to_csv('x_test.csv')

In [9]:
y_train_df.to_csv('y_train.csv')
y_test_df.to_csv('y_test.csv')
y_validate_df.to_csv('y_validate.csv')